application: hyper-fen 
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /.*
  script: _go_app
